version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  target-branch: "master"
  open-pull-requests-limit: 10

- package-ecosystem: "github-actions"
  # Workflow files stored in the
  # default location of `.github/workflows`
  directory: "/.github/workflows"
  schedule:
    interval: "daily"
